=== workcontrolgit/CrystalReportWebAPI/CrystalReportWebAPI/Reports/ReportData/product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Product" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Product">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Product_ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="Product Type ID" index-key="Product_Type_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Supplier ID" index-key="Supplier_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Product_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1110"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Product_Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2925"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Color" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1260"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Size" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="735"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="M_x002F_F" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="705"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Price_SRP" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1230"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="$#,##0.00;($#,##0.00)"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Product_Type_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="390"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Product_Class" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1440"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Supplier_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== workcontrolgit/CrystalReportWebAPI/CrystalReportWebAPI/Reports/ReportData/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="product.xsd" generated="2007-07-31T19:01:56">
<Product>
<Product_ID>1101</Product_ID>
<Product_Name>Active Outdoors Crochet Glove</Product_Name>
<Size>xsm</Size>
<Price_SRP>14.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1102</Product_ID>
<Product_Name>Active Outdoors Crochet Glove</Product_Name>
<Size>sm</Size>
<Price_SRP>14.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1103</Product_ID>
<Product_Name>Active Outdoors Crochet Glove</Product_Name>
<Size>med</Size>
<Price_SRP>14.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1104</Product_ID>
<Product_Name>Active Outdoors Crochet Glove</Product_Name>
<Size>lrg</Size>
<Price_SRP>14.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1105</Product_ID>
<Product_Name>Active Outdoors Crochet Glove</Product_Name>
<Size>xlrg</Size>
<Price_SRP>14.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1106</Product_ID>
<Product_Name>Active Outdoors Lycra Glove</Product_Name>
<Size>xxsm</Size>
<Price_SRP>16.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1107</Product_ID>
<Product_Name>Active Outdoors Lycra Glove</Product_Name>
<Size>xsm</Size>
<Price_SRP>16.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1108</Product_ID>
<Product_Name>Active Outdoors Lycra Glove</Product_Name>
<Size>sm</Size>
<Price_SRP>16.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1109</Product_ID>
<Product_Name>Active Outdoors Lycra Glove</Product_Name>
<Size>med</Size>
<Price_SRP>16.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1110</Product_ID>
<Product_Name>Active Outdoors Lycra Glove</Product_Name>
<Size>lrg</Size>
<Price_SRP>16.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>1111</Product_ID>
<Product_Name>Active Outdoors Lycra Glove</Product_Name>
<Size>xlrg</Size>
<Price_SRP>16.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>1</Supplier_ID>
</Product>
<Product>
<Product_ID>2201</Product_ID>
<Product_Name>Triumph Pro Helmet</Product_Name>
<Color>black</Color>
<Size>sm</Size>
<Price_SRP>41.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2202</Product_ID>
<Product_Name>Triumph Pro Helmet</Product_Name>
<Color>white</Color>
<Size>sm</Size>
<Price_SRP>41.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2203</Product_ID>
<Product_Name>Triumph Pro Helmet</Product_Name>
<Color>black</Color>
<Size>med</Size>
<Price_SRP>41.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2204</Product_ID>
<Product_Name>Triumph Pro Helmet</Product_Name>
<Color>white</Color>
<Size>med</Size>
<Price_SRP>41.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2205</Product_ID>
<Product_Name>Triumph Pro Helmet</Product_Name>
<Color>black</Color>
<Size>lrg</Size>
<Price_SRP>41.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2206</Product_ID>
<Product_Name>Triumph Pro Helmet</Product_Name>
<Color>white</Color>
<Size>lrg</Size>
<Price_SRP>41.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2207</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>black</Color>
<Size>sm</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2208</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>red</Color>
<Size>sm</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2209</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>white</Color>
<Size>sm</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2210</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>black</Color>
<Size>med</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2211</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>red</Color>
<Size>med</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2212</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>white</Color>
<Size>med</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2213</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>black</Color>
<Size>lrg</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2214</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>red</Color>
<Size>lrg</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>2215</Product_ID>
<Product_Name>Triumph Vertigo Helmet</Product_Name>
<Color>white</Color>
<Size>lrg</Size>
<Price_SRP>53.9</Price_SRP>
<Product_Type_ID>6</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>2</Supplier_ID>
</Product>
<Product>
<Product_ID>3301</Product_ID>
<Product_Name>Guardian Chain Lock</Product_Name>
<Price_SRP>4.5</Price_SRP>
<Product_Type_ID>7</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>3</Supplier_ID>
</Product>
<Product>
<Product_ID>3302</Product_ID>
<Product_Name>Guardian &quot;U&quot; Lock</Product_Name>
<Price_SRP>17.5</Price_SRP>
<Product_Type_ID>7</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>3</Supplier_ID>
</Product>
<Product>
<Product_ID>3303</Product_ID>
<Product_Name>Guardian XL &quot;U&quot; Lock</Product_Name>
<Price_SRP>19.9</Price_SRP>
<Product_Type_ID>7</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>3</Supplier_ID>
</Product>
<Product>
<Product_ID>3304</Product_ID>
<Product_Name>Guardian ATB Lock</Product_Name>
<Price_SRP>21.9</Price_SRP>
<Product_Type_ID>7</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>3</Supplier_ID>
</Product>
<Product>
<Product_ID>3305</Product_ID>
<Product_Name>Guardian Mini Lock</Product_Name>
<Price_SRP>21.9</Price_SRP>
<Product_Type_ID>7</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>3</Supplier_ID>
</Product>
<Product>
<Product_ID>4101</Product_ID>
<Product_Name>InFlux Crochet Glove</Product_Name>
<Size>sm</Size>
<Price_SRP>13.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>4</Supplier_ID>
</Product>
<Product>
<Product_ID>4102</Product_ID>
<Product_Name>InFlux Crochet Glove</Product_Name>
<Size>med</Size>
<Price_SRP>13.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>4</Supplier_ID>
</Product>
<Product>
<Product_ID>4103</Product_ID>
<Product_Name>InFlux Crochet Glove</Product_Name>
<Size>lrg</Size>
<Price_SRP>13.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>4</Supplier_ID>
</Product>
<Product>
<Product_ID>4104</Product_ID>
<Product_Name>InFlux Lycra Glove</Product_Name>
<Size>sm</Size>
<Price_SRP>15.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>4</Supplier_ID>
</Product>
<Product>
<Product_ID>4105</Product_ID>
<Product_Name>InFlux Lycra Glove</Product_Name>
<Size>med</Size>
<Price_SRP>15.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>4</Supplier_ID>
</Product>
<Product>
<Product_ID>4106</Product_ID>
<Product_Name>InFlux Lycra Glove</Product_Name>
<Size>lrg</Size>
<Price_SRP>15.5</Price_SRP>
<Product_Type_ID>5</Product_Type_ID>
<Product_Class>Accessory</Product_Class>
<Supplier_ID>4</Supplier_ID>
</Product>
<Product>
<Product_ID>5201</Product_ID>
<Product_Name>Xtreme Adult Helmet</Product_Name>
